"""Added battles table

Revision ID: 4487350e4659
Revises: 
Create Date: 2022-04-11 13:02:45.683219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4487350e4659'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Battles',
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Battles')
    # ### end Alembic commands ###
