"""Added classes table

Revision ID: 126e33931724
Revises: 
Create Date: 2022-04-11 02:10:33.132099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '126e33931724'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Classes',
    sa.Column('class', sa.VARCHAR(length=50), nullable=False),
    sa.Column('type', sa.VARCHAR(length=2), nullable=False),
    sa.Column('country', sa.VARCHAR(length=20), nullable=False),
    sa.Column('numGuns', sa.SMALLINT(), nullable=True),
    sa.Column('bore', sa.REAL(), nullable=True),
    sa.Column('displacement', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('class')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Classes')
    # ### end Alembic commands ###
