"""Added ships table

Revision ID: 77e0aeb0d6db
Revises: 
Create Date: 2022-04-11 11:58:20.686377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77e0aeb0d6db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Ships',
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('class', sa.VARCHAR(length=50), nullable=False),
    sa.Column('launched', sa.SMALLINT(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Ships')
    # ### end Alembic commands ###
